name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  # 🔹 Job 1 : Tests
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

  # 🔹 Job 2 : Build + Push Docker
  build_and_push:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build + Push vers 2 repos
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            abidjan2020/flaskapp2:latest
            abidjan2020/faskapp:latest





  notify:
  runs-on: ubuntu-latest
  needs: [tests, build_and_push]
  if: failure()

  steps:
    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ciabidjan51@gmail.com
        password: Abidjan2020.
        subject: "Échec du pipeline CI/CD"
        to: tonemailperso@gmail.com
        from: ${{ secrets.EMAIL_USERNAME }}
        body: |
          Le pipeline CI/CD a échoué.
          Vérifiez les logs sur GitHub Actions.
